### ISSUE TITLE
Prettify and Update Install Subcommand 🤖

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/kubearmor-client#109]
Current `karmor install` command looks bleak, we need to jazz up the installation experience with some 🚀 🤖 😸  emojis and perhaps animations as well.

We currently just instantiate kubernetes api calls and leave checking the status of the installation to the user. We should wait for the various installations to be successful and only exit once kubearmor is running. This wait time also gives us some room to play animations for a better experience 😄 

**Work Items**
- [x] Wait for KubeArmor to start running before exiting the `install` subcommand
- [x] Jazz Up the Experience

**Comment by aishwarya25252** [comment]
Hey , I would like to take up this issue and work on it .

**Comment by nyrahul** [comment]
@aishwarya25252 , any updates on this? Very much looking forward to this.
