### ISSUE TITLE
Allow karmor to verify the existence of namespace before watching for alerts

### ISSUE THREAD

**Issue by kranurag7** [kubearmor/kubearmor-client#126]
`karmor log` is starting to watch for alerts even if the namespace doesn't exist in the cluster. 

```
$ kubectl get ns
NAME              STATUS   AGE
default           Active   9d
kube-node-lease   Active   9d
kube-public       Active   9d
kube-system       Active   9d
wordpress-mysql   Active   6m9s

$ karmor log --namespace wordpress-demo
gRPC server: localhost:32767
Created a gRPC client (localhost:32767)
Checked the liveness of the gRPC server
Started to watch alerts
```
- In the example above, there is no namespace with name `wordpress-demo` but `karmor` is looking for alerts in this case. 

### Expected Behaviour 
- `karmor` should check for namespaces first and only after post verification, it should look for alerts if the namespace exist.

**Comment by nyrahul** [comment]
Hey, this may not be the correct way to handle.
What if the user executes the karmor log command and then creates a deployment in the wordpress-demo namespace ? The events will start streaming as and when they appear.

**Comment by kranurag7** [comment]
I agree with your point here. Thank you very much.
