### ISSUE TITLE
`karmor summary` not showing pods infos

### ISSUE THREAD

**Issue by yasin-cs-ko-ak** [kubearmor/kubearmor-client#172]
```
➜  ~ karmor summary
Error: rpc error: code = Unimplemented desc = unknown service v1.observability.Observability
```
When I run `karmor summary` command that is the output.

Also port-forward is working fine.
```
➜  ~ kubectl port-forward -n explorer service/knoxautopolicy --address 0.0.0.0 --address :: 9089:9089 &                           
[1] 25901
➜  ~ Forwarding from 0.0.0.0:9089 -> 9089
Forwarding from [::]:9089 -> 9089
Handling connection for 9089
```
But I still get this error.

**Comment by Ankurk99** [comment]
Can you please confirm that you are using the latest version of discovery-engine? The default deployment yaml in the README installs the stable release, please try updating it to latest instead.

**Comment by yasin-cs-ko-ak** [comment]
Yes.  I am currently using `kubectl apply -f https://raw.githubusercontent.com/accuknox/discovery-engine/dev/deployments/k8s/deployment.yaml` this YAML for installation.  
But still  I am getting the same error.

**Comment by seswarrajan** [comment]
Hello @yasin-cs-ko-ak
The stable image is not updated to point to the latest, hence the issue. 
Try changing the image version from **accuknox/knoxautopolicy:stable** to **accuknox/knoxautopolicy:latest**

**Comment by seswarrajan** [comment]
@yasin-cs-ko-ak 
The stable release has changes related to summary. Please use the latest stable image for discovery -engine and latest of karmor CLI.

**Comment by yasin-cs-ko-ak** [comment]
@seswarrajan 
It is working fine. 
```
➜  ~ karmor summary --pod adservice-694f4ff98-cgl8m

  Pod Name        adservice-694f4ff98-cgl8m  
  Namespace Name  default                    
  Cluster Name    default                    
  Container Name  server                     
  Labels          app=adservice              

Process Data
+---------------+--------------------------+-------+------------------------------+--------+
|  SRC PROCESS  | DESTINATION PROCESS PATH | COUNT |      LAST UPDATED TIME       | STATUS |
+---------------+--------------------------+-------+------------------------------+--------+
| /usr/bin/runc | /bin/grpc_health_probe   | 83    | Mon Sep 19 10:45:52 UTC 2022 | Allow  |
+---------------+--------------------------+-------+------------------------------+--------+
```
This issue can be closed. 
Thank you @seswarrajan

**Comment by seswarrajan** [comment]
Thanks @yasin-cs-ko-ak
