### ISSUE TITLE
handling policy-templates 

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/kubearmor-client#176]
Prepare rules.yaml based on [policy-templates repo](https://github.com/kubearmor/policy-templates/).

- [ ] prepare sample metadata.yaml
- [ ] prepare release of policy-templates
- [ ] `karmor recommend --update`
- [ ] `karmor recommend` check whether latest policy-templates are available.

**Comment by vishnusomank** [comment]
Hi, @nyrahul @wazir-ahmed I've raised a draft PR for the same can you take a look at it and suggest if any changes or improvements are needed?
PR : [https://github.com/kubearmor/kubearmor-client/pull/180](https://github.com/kubearmor/kubearmor-client/pull/180)
