### ISSUE TITLE
discovery-engine installation as part of karmor install

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/kubearmor-client#183]
[Discovery-engine](https://github.com/kubearmor/discovery-engine) is an observability and automated security posture identification engine that works on top of with kubearmor visibility.

Currently, the installation of discovery-engine has to be handled separately. It would be good to install discovery-engine as part of `karmor install`.

Note that the deployment of the discovery-engine has to happen using the existing [deployment yaml](https://github.com/kubearmor/discovery-engine/blob/dev/deployments/k8s/deployment.yaml) of the discovery-engine without having to rewrite deployment config in kubearmor-client.

**Comment by Ankurk99** [comment]
Discovery-engine has been moved under accuknox org and is no longer part of KubeArmor project.
