### ISSUE TITLE
Install KubeArmor in non kube-system namespace

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/kubearmor-client#21]
Karmor currently install kubearmor by default in kube-system namespace.
There should be an option to use a different namespace.

**Comment by saurabhshendye** [comment]
@nyrahul is this issue up for grabs? If so I would love to contribute. 🙂

**Comment by nyrahul** [comment]
Many thanks for picking this up @saurabhshendye . CC: @daemon1024
