### ISSUE TITLE
`karmor uninstall` script with terminating progress and emojis for status

### ISSUE THREAD

**Issue by yasin-cs-ko-ak** [kubearmor/kubearmor-client#225]
As of now we have `karmor install` that shows kubearmor pods installation progress along with running progress.

It's good to have `karmor uninstall` script that shows process with emojis plus terminating progress so we don't have to check the pod's status manually when pods are terminating.

**Comment by MdSahil-oss** [comment]
@yasin-cs-ko-ak I would like to work on this.
