### ISSUE TITLE
refactor discover pkg apis

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/kubearmor-client#241]
Currently discover pkg apis i.e. `ConvertPolicy()` and `Policy()` and are not usable outside. The discovered policies are printed to `stdout` only. if we can make these apis to return the encoded policies then we can utilize them outside. for example, we can leverage these apis in ginkgo based auto-testing framework for `discovery-engine` where it will no longer required to handle policy data from standard output.

**Comment by Prateeknandle** [comment]
Hey @rksharma95 can we also do te same for `summary` api, want to ask is it doable for summary?

**Comment by rksharma95** [comment]
> Hey @rksharma95 can we also do te same for `summary` api, want to ask is it doable for summary?

Yes it is. :+1:
