### ISSUE TITLE
fix:  uneven indentation on `karmor install` 

### ISSUE THREAD

**Issue by yasin-cs-ko-ak** [kubearmor/kubearmor-client#248]
Fix the uneven indentation on `karmor install` script as shown below
![image](https://user-images.githubusercontent.com/92008211/214252614-c57bcd53-888e-4f95-bc11-d722dbbcc2ee.png)

**Comment by EswaramoorthyS** [comment]
Hi, 
Can I take up this issue? if nobody's working on it.
thank you

**Comment by yasin-cs-ko-ak** [comment]
> Hi, Can I take up this issue? if nobody's working on it. thank you

@EswaramoorthyS Thank you for your interest to working on this and yes you can take this up.
