### ISSUE TITLE
SELinux configuration

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/kubearmor-client#25]
Currently we default to AppArmor based deploment in any environment. 
We should also autodetect the underlying LSM in node and install based on that.

**Comment by AvineshTripathi** [comment]
Hey @daemon1024 I am looking forward this issue, can you give more description to the issue also some navigation to the locations where I ll have to play

**Comment by daemon1024** [comment]
Hey @AvineshTripathi , Thanks a lot for taking this up.

So currently kArmor just installs with AppArmor mounts. Ref https://github.com/kubearmor/KubeArmor/blob/main/deployments/get/defaults.go#L64-L77=

But we won't need these or these may not exist if the underlying LSM is not AppArmor.

So essentially we would need a way to detect the underlying LSM in our [auto detection mechanism](https://github.com/kubearmor/kubearmor-client/blob/c9431d1b17247692627f6ed8b3e8af6a1b2fc2ce/install/install.go#L230) and pass it onto the kubearmor deployments get package for further processing.

For further queries feel free to reach out in this thread or on Slack :)

**Comment by daemon1024** [comment]
We don't support k8s deployments for SELinux so deferring this issue.

Related work item could be https://github.com/kubearmor/KubeArmor/issues/788 and the corresponding changes to here in kArmor.
