### ISSUE TITLE
Karmor probe update to show security posture per namespace

### ISSUE THREAD

**Issue by PrimalPimmy** [kubearmor/kubearmor-client#250]
`karmor probe` command shows namespace based posture for the entire node. 
Once https://github.com/kubearmor/KubeArmor/pull/832 gets merged, probe command should have a new column containing security postures on a namespace level if annotations have been set for the same.

**Comment by DelusionalOptimist** [comment]
@PrimalPimmy is this related to #269?

**Comment by PrimalPimmy** [comment]
@DelusionalOptimist This is more related to that how we can change default security postures on the namespace level using annotations, but that is not shown here if the the security posture has changed

**Comment by DelusionalOptimist** [comment]
Yes, I think it is good to close. Thanks @Aryan-sharma11!
