### ISSUE TITLE
`karmor install --save should work without any running cluster

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/kubearmor-client#252]
**Description**
Currently `karmor install --save` which is used to save the k8s manifest depends upon the k8s environment. If there is no k8s cluster running then the command fails. 

**Solution**
The aim is to pass the environment as an argument with the command, like: `karmor install --save k3s`. 

**Ref:** https://github.com/kubearmor/kubearmor-client/blob/main/install/install.go#L149-L151

**Comment by TheRealSibasishBehera** [comment]
Hi @Ankurk99,  I would like to work on this issue
