### ISSUE TITLE
Fix go-sec issues 

### ISSUE THREAD

**Issue by PrimalPimmy** [kubearmor/kubearmor-client#259]
The CI for go-sec fails due to some unhandled errors in some packages. Ref: https://github.com/kubearmor/kubearmor-client/actions/runs/4106954987/jobs/7085843416.

**Comment by DepressedSage** [comment]
I'd like to work on this

**Comment by PrimalPimmy** [comment]
Nice! Assigning it to you :D

**Comment by DepressedSage** [comment]
Thank you!
