### ISSUE TITLE
`karmor probe` doesn't group armored up pods according to namespace

### ISSUE THREAD

**Issue by DelusionalOptimist** [kubearmor/kubearmor-client#269]
### Current behavior
When running karmor probe, it shows applied security policies according to kubernetes namespace however the grouping is random and difficult to interpret. See attached screenshot and how different policies in same ns are present in different row groups.
![Screenshot from 2023-02-15 11-26-58](https://user-images.githubusercontent.com/54525605/218947002-dde374ba-ded5-4ef3-b34b-4c7a88c500d2.png)

### Expected behavior
Better grouping of policies according to namespace.

**Comment by Aryan-sharma11** [comment]
Hey, I would like to work on this issue.
