### ISSUE TITLE
karmor unable to port forward

### ISSUE THREAD

**Issue by DelusionalOptimist** [kubearmor/kubearmor-client#273]
**Current Behaviour**
`karmor logs`, `summary` and `discover` fail to port forward internally.

**Environment**
karmor version - `0.11.7 linux/amd64`
k8s -`v1.24.9`
k8s platform - `AKS` (maybe other managed platforms too)

**Logs**
```
$ karmor logs
local port to be used for port forwarding kubearmor-relay-64c6fff875-z98zd: 32767
Error:
could not do kubearmor portforward, error=could not create port forward error upgrading connection: error sending request: Post "https://erfornance-benchmarking3-dns-e5f89e12.hcp.eastus.azmk8s.io:443/api/v1/namespaces/kube-system/pods/kubearmor-relay-64c6fff875-z98zd/portforward": dial tcp: lookup erfornance-benchmarking3-dns-e5f89e12.hcp.eastus.azmk8s.io on 192.168.29.1:53: no such host
```

**Expected Behaviour**
karmor should port forward internally and the user shouldn't have to use kubectl port-forward

**Comment by kranurag7** [comment]
This was handled [here](https://github.com/kubearmor/kubearmor-client/issues/190). @rajaSahil Would you have some time to take a look at this, please?

**Comment by Aryan-sharma11** [comment]
Hey, I tried looking into this issue, but wasn't able to reproduce it

**Comment by DelusionalOptimist** [comment]
Folks, I went through the code and found what's happening. Though it's a small fix but since reproducing this has been awkward, I'm raising a quick PR.
