### ISSUE TITLE
installed message should be change

### ISSUE THREAD

**Issue by Amishakumari544** [kubearmor/kubearmor-client#293]
When I installed the karmor and check the version, I am getting this as output message:
![image](https://user-images.githubusercontent.com/49230384/225103124-6af0a29a-1b2c-4bf5-b3e2-39fd65972f23.png)

And when I mistakenly tried to run the `karmor install` again it's giving this message as an output:

![image](https://user-images.githubusercontent.com/49230384/225103401-f7fd9677-dbb5-4863-b03f-ea2784eebc99.png)

Is this a correct message to be displayed when a user mistakenly type the install command?

cc - @nyrahul @Ankurk99 @kranurag7

**Comment by kranurag7** [comment]
Hey @Amishakumari544 The message when you invoked `karmor install` is correct. The Error indicates that you don't have a supported Kubernetes environment running. You can look at the valid environments here.
https://github.com/kubearmor/kubearmor-client/blob/e8c372c2eefd98b90579a7f40e10ddc41504b763/install/install.go#L54

**Comment by Amishakumari544** [comment]
yes, the correct installation output should be this:
![image](https://user-images.githubusercontent.com/49230384/225108099-dc03c775-7d9b-402c-817c-69c057efeb32.png)


I am just confirming if the above output message is correct or not?

**Comment by Amishakumari544** [comment]
Also, I followed these steps from this [file](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/deployment_guide.md)

![image](https://user-images.githubusercontent.com/49230384/225109449-aac65600-06ab-46e2-8837-cd30457073d2.png)
Is this a correct way?

**Comment by kranurag7** [comment]
Yes, the screenshot you shared is perfect. That's the appropriate way to get up & running with kubearmor on k3s.
