### ISSUE TITLE
`karmor profile` doesn't exit TUI mode on gRPC service connection errors

### ISSUE THREAD

**Issue by DelusionalOptimist** [kubearmor/kubearmor-client#294]
**Current behavior**
When a user runs `karmor profile` it tries to connect with the gRPC server either running in kubearmor-relay service or through the gRPC port specified through `--gRPC` flag and get visibility logs.
However, if it fails to connect, it still keeps showing the TUI with no events. This is misleading and might make users be under the impression that no logs are coming in.

**Expected behavior**
Quit TUI mode when connection with gRPC service doesn't succeed.

**Comment by DelusionalOptimist** [comment]
Thanks @zhy76. Let us know if you need any help.

**Comment by rootxrishabh** [comment]
Hi @DelusionalOptimist, I am having trouble reproducing this error, can you help out?

**Comment by DelusionalOptimist** [comment]
Hey @rootxrishabh this has actually been fixed recently along with other improvements in #348 : (
