### ISSUE TITLE
Add `karmor probe` as a part of `karmor sysdump`

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/kubearmor-client#305]
**Description**
Currently `karmor sysdump` generated output doesn't contains information about the node's support for KubeArmor (available LSMs, the mode of enforcement, etc.) which are already a part of `karmor probe`. 
The aim is to get that output as a part of `karmor sysdump`

**Comment by legorie** [comment]
Hi @Ankurk99 , the probing for KubeArmor support happens only when KubeArmor is not running isn't it ?
```
$ karmor probe

Didn't find KubeArmor in systemd or Kubernetes, probing for support for KubeArmor                                                     
                                                                                                                                      
Host:                                                                                                                                 
         Observability/Audit: Supported (Kernel Version 5.15.0)                                                                       
         Enforcement: Full (Supported LSMs: lockdown,capability,landlock,yama,apparmor)   
```
So, when the KubeArmor is not running the new requirement is that the `karmor sysdump` creates a new file with the node support information. Or, is there an existing file which we can use like `node-info.yaml` ?

**Comment by rootxrishabh** [comment]
Hi @Ankurk99, to my understanding [this function](https://github.com/kubearmor/kubearmor-client/blob/57de131708d7e3eb4f2a55beba93f3b1fda022fc/probe/probe.go#L448) has to be included into the sysdump file. Is this correct?

**Comment by rootxrishabh** [comment]
As I see, the node information in the give image obtained by running "karmor probe" is to be included into the output dump of "karmor sysdump". Am I correct @Ankurk99 ?
![Screenshot from 2023-08-10 01-30-16](https://github.com/kubearmor/kubearmor-client/assets/73490663/a1018cff-88ac-4a71-970e-afafe9cbd966)

**Comment by Ankurk99** [comment]
@rootxrishabh Ideally we would love to see everything from the `karmor probe` in `sysdump` including if the KubeArmor is running fine and the image versions.

**Comment by rootxrishabh** [comment]
Sysdump shows inconsistent behaviour while running. As shown below.
![Screenshot from 2023-09-06 00-02-00](https://github.com/kubearmor/kubearmor-client/assets/73490663/2a04c52a-1642-4d6d-9af6-da335eb08f77)

**Comment by sheharyaar** [comment]
Hi @rootxrishabh , are you still working on it ? I would like to take this up. @Ankurk99 are you talking about the output to stdout or to the zip created ?

**Comment by rootxrishabh** [comment]
Hey @sheharyaar, not working on this as of now, go ahead : )

**Comment by Ankurk99** [comment]
>Hi @rootxrishabh , are you still working on it ? I would like to take this up. @Ankurk99 are you talking about the output to stdout or to the zip created ?

@sheharyaar Ideally, both.

**Comment by sheharyaar** [comment]
Thanks for assigning this, will follow up if I have a query or a PR is ready.

**Comment by sheharyaar** [comment]
I checked that `karmor probe` accepts namespace , format string, grpc and other flags. So how do I tackle those in `karmor sysdump` do I default the namespace to _kubearmor_ and `--full` flag to _true_, or do I add these flags to sysdump ? @Ankurk99

**Comment by sheharyaar** [comment]
Also, the probe dump would be in yaml format or just a raw stdout dump (karmor-probe.dump) ?

**Comment by sheharyaar** [comment]
@Ankurk99

**Comment by Manik2708** [comment]
I am interested on working this issue!

**Comment by Manik2708** [comment]
Also do we want to print the output in terminal or save in zip file?

**Comment by Manik2708** [comment]
I am interested on working on this issue! @Ankurk99

**Comment by Manik2708** [comment]
@DelusionalOptimist @daemon1024
