### ISSUE TITLE
Support for gRPC flag in karmor recommend 

### ISSUE THREAD

**Issue by vishnusomank** [kubearmor/kubearmor-client#317]
The `karmor recommend` connects with Discovery Engine to recommend admission controller policies. A gRPC connection is initiated by the `karmor` client to query and get the necessary information from Discovery Engine. With the current implementation the `karmor recommend` can only create a connection to Discovery Engine running on a Kubernetes cluster. 

Ideally, We would require a `gRPC` flag pointing to the `IP:PORT` used by the discovery engine regardless of where it is running.

```
karmor recommend -n wordpress-mysql -r report.html --gRPC :9089
```

**Comment by sheharyaar** [comment]
Hi @vishnusomank , is this fixed yet or is someone working on this ? I would love to give this a try.

**Comment by vishnusomank** [comment]
@Ankurk99

**Comment by Ankurk99** [comment]
@sheharyaar Thanks for your interest. We are in the process of removing `karmor` dependency on any external tool (here discovery-engine) and hence won't need to add this support. 
Ideally, karmor recommend will provide policy recommendations based on https://github.com/kubearmor/policy-templates, independent of any external tools.

**Comment by Ankurk99** [comment]
@vishnusomank Can we close this issue?

**Comment by vishnusomank** [comment]
Sure @Ankurk99. 

@sheharyaar  Thanks again for showing interest. 

Closing this since we are removing the external dependency from `karmor`
