### ISSUE TITLE
docs: broken-link-check

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/kubearmor-client#350]
Automatically validate if there are any broken-links or missing images in the documentation.

## Tasks
- [ ] GH action based on [broken-link-check](https://github.com/marketplace/actions/broken-link-check)

**Comment by yashvardhanmishra** [comment]
Hi @nyrahul I would like to work on this issue , please assign me this issue

**Comment by nyrahul** [comment]
> Hi @nyrahul I would like to work on this issue , please assign me this issue

Hey, Thank you for your interest. Let us know if any discuss/clarification needed. We are always on [the slack](https://join.slack.com/t/kubearmor/shared_invite/zt-1ltmqdbc6-rSHw~LM6MesZZasmP2hAcA/).

**Comment by nyrahul** [comment]
@yashvardhanmishra , any updates on this? Let us know if you have any questions.
