### ISSUE TITLE
karmor probe panic

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/kubearmor-client#385]
https://github.com/kubearmor/kubearmor-client/blob/7b409be695906356db6f6f0f9beb42fd8245e350/probe/probe.go#L767

We have seen panics on this line of the code reported by users. Potentially the map access should be validated before appending the data.

![image](https://github.com/kubearmor/kubearmor-client/assets/47106543/822d91f9-1c27-44b4-b29e-150a96fed04e)

**Comment by 20RitikSingh** [comment]
I want to work on this.

**Comment by akagami-harsh** [comment]
@daemon1024, i can see the PR is not yet merged can i give it a try

**Comment by partik03** [comment]
@daemon1024 Please assign it to me

**Comment by Manik2708** [comment]
Is this issue still alive?

**Comment by daemon1024** [comment]
Nope. Thanks @partik03 for the fix!
