### ISSUE TITLE
`karmor install --env=generic --save` should work without kubernetes cluster access

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/kubearmor-client#386]
With the updates in `karmor install` It tries to create namespace if not found.

This logic prevents user without kubernetes to just generate the manifest. If `--save` is used, karmor should not fail if k8s env is not found, it should just go ahead and use the provided env or use the generic env to generate the manifest file.

![image](https://github.com/kubearmor/kubearmor-client/assets/47106543/3cee1c5e-c2fe-4379-a1b7-7a56e12adebe)

**Comment by sheharyaar** [comment]
I would like to work on this one.

**Comment by sheharyaar** [comment]
created a PR, please review.

**Comment by daemon1024** [comment]
Thanks @sheharyaar again for handling it. Appreciate it.
