### ISSUE TITLE
karmor install percentage completion showing more than 100%

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/kubearmor-client#393]
![image](https://github.com/kubearmor/kubearmor-client/assets/9133227/d27d7f1f-af15-4849-983b-b58cbcccee23)

Steps to reproduce:
[Download the karmor tool](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/deployment_guide.md#install-karmor-cli-optional) and use `karmor install` to install kubearmor.

**Comment by partik03** [comment]
@nyrahul please assign it to me

**Comment by EraKin575** [comment]
@nyrahul is this issue still pending for some reason? If yes, I would like to work on it

**Comment by nyrahul** [comment]
There seems to be [a PR](https://github.com/kubearmor/kubearmor-client/pull/394) already present for this. Not sure if it handles the problem in the right way. I have pinged for the review.

**Comment by daemon1024** [comment]
@nyrahul we handled this as part of 
- #402

We don't have a progress bar anymore
![image](https://github.com/kubearmor/kubearmor-client/assets/47106543/62a86312-b1aa-4ab2-b465-90a1150d3d73)

Thanks folks for the interest. Helm bases installation is still new. If you think there's something we can improve, do point it out.
