### ISSUE TITLE
update `karmor install` to deploy kubearmor-relay sa and associated rbac policies for kubearmor relay

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/kubearmor-client#397]
Ref: https://github.com/kubearmor/KubeArmor/issues/1525

**Comment by Utkar5hM** [comment]
I would like to work on updating the changes here.

**Comment by rksharma95** [comment]
Hello @Utkar5hM , there's a work-in-progress task https://github.com/kubearmor/kubearmor-client/pull/396 to shift the installation method to Helm. This means there will be no need to manually add Kubernetes resources anymore. we can close this issue, thanks!

**Comment by rootxrishabh** [comment]
@rksharma95, karmor will still preserve legacy installation and uninstallation. This issue still might be relevant wdyt?

**Comment by rksharma95** [comment]
@rootxrishabh In that case it make sense to handle this issue. Reopened it.
cc: @daemon1024
