### ISSUE TITLE
fix scorecard github action

### ISSUE THREAD

**Issue by kranurag7** [kubearmor/kubearmor-client#420]
The following has been failing on main for a while now and this issue tracks fixing the same. 

https://github.com/kubearmor/kubearmor-client/actions/workflows/scorecard.yml

Please ask if you've any questions w.r.t. the issue.

**Comment by tico88612** [comment]
Hi, @kranurag7 

Can I take on this?

**Comment by kranurag7** [comment]
Sure, thank you very much. Please ask here or ping me on slack if you've questions around this.
