### ISSUE TITLE
`karmor uninstall` should remove annotations/policies by default

### ISSUE THREAD

**Issue by DelusionalOptimist** [kubearmor/kubearmor-client#434]
### Description

Currently when users remove KubeArmor with `karmor uninstall`, by default there pods are left with AppArmor annotations.
This is not desired as it may cause issues in certain cases like:
- AppArmor policies were deleted manually
- Enforcer was changed to BPF LSM and apparmor was disabled
etc.

They have to use `--force` flag for the same which is also not documented anywhere.

### Improvement
Remove annotations and policies/CR(D)s by default.
If user wants to keep it, they use the `--keep-policies` flag. (Could use suggestions on the flag name)

**Comment by Ishaanj18** [comment]
Can I work on this issue?

**Comment by rootxrishabh** [comment]
Related - #[1589](https://github.com/kubearmor/KubeArmor/issues/1589)
