### ISSUE TITLE
`karmor sysdump` should contain logs from all pods with `kubearmor-app` label

### ISSUE THREAD

**Issue by DelusionalOptimist** [kubearmor/kubearmor-client#441]
### Description

Currently `karmor sysdump` command only takes logs from pods with the label `kubearmor-app=kubearmor` however for debugging purposes, logs from other components like kubearmor-relay-server, kubearmor-controller and kubeamor-operator might be required as well.

### Solution

Get the logs from all pods which have the `kubearmor-app` label so that we can get more insights while debugging.

**Comment by Ishaanj18** [comment]
Can I work on this issue?
