### ISSUE TITLE
`karmor sysdump`: generated `.*apparmor.tar.gz` is not actually a gzip tar

### ISSUE THREAD

**Issue by DelusionalOptimist** [kubearmor/kubearmor-client#458]
## Description
`karmor sysdump` generates some data for debugging which also includes all the generated AppArmor profiles.
The entire `/etc/apparmor.d` directory is converted to tar and dumped with the extension `.tar.gz` however it is not gzipped.

Ref - https://github.com/kubearmor/kubearmor-client/blob/main/sysdump/sysdump.go#L252

## Possible Solution
Make it a gzip or change the file extension.
Additional refactor can be done as well to make the function a little generic.

**Comment by rissh** [comment]
Hey @DelusionalOptimist ,

I want to give it a try and work on this issue. Can you please assign me this issue?
Please feel free to give me any suggestions or guidance as I work on this task. I'm open to feedback and would appreciate any insights you have.

Thank you!
