### ISSUE TITLE
Use go 1.18 buildinfo for version output 

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/kubearmor-client#55]
go 1.18 introduced a new `debug/buildinfo` package which should eliminate the need of manually embedding version info using build flags.

Let's use it for our versioning information

Ref https://go.dev/doc/go1.18#debug/buildinfo

**Comment by nthnieljson** [comment]
hello, I would like to try working on this issue

**Comment by Akshit42-hue** [comment]
Can I work on it @daemon1024

**Comment by daemon1024** [comment]
Hey @nthnieljson, are you still working on this? If not we can assign it to @Akshit42-hue

**Comment by s1ntaxe770r** [comment]
For anyone looking for some pointers here's an example 
https://github.com/kelseyhightower/buildinfo

**Comment by Akshit42-hue** [comment]
Should I go ahead @daemon1024

**Comment by daemon1024** [comment]
@Akshit42-hue let me know if you are still working this, will reassign you 😄 Thank You!

**Comment by osBins** [comment]
Hi I'd like to work on this issue! :D

**Comment by daemon1024** [comment]
Deferred till we have the relevant issue is handled in upstream 😄 Thanks for looking into this!
