### ISSUE TITLE
Sysdump Utility

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/kubearmor-client#9]
Ref https://github.com/kubearmor/KubeArmor/issues/110

Dump List:
- [x] Nodes Info ( Contains System Information as well )
- [x] k8s Version
- [x] KubeArmor DaemonSet
- [x] KubeArmor Pod Logs
- [ ] Audit Log
- [x] Policy Yamls

**Comment by nyrahul** [comment]
- [ ] kubectl describe
- [ ] gzip /etc/apparmor.d
- [ ] dmesg
- [ ] copy /boot/config-$(uname -r)
- [ ] uname -a
- [ ] bpftool prog list
- [ ] lsm file /sys/kernel/security/lsm
